CREATE TABLE `Metals`
(
    `id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    `metal` NVARCHAR(160) NOT NULL,
    `price` NUMERIC(7,2) NOT NULL
);

CREATE TABLE `Styles`
(
    `id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    `style` NVARCHAR(160) NOT NULL,
    `price` NUMERIC(7,2) NOT NULL
);

CREATE TABLE `Sizes`
(
    `id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    `carets` NUMERIC(4,2) NOT NULL,
    `price` NUMERIC(7,2) NOT NULL
);

CREATE TABLE `Orders` (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  metalId INTEGER NOT NULL,
  styleId INTEGER NOT NULL,
  sizeId INTEGER NOT NULL,
  timestamp DATETIME DEFAULT CURRENT_DATE,
  FOREIGN KEY (metalId) REFERENCES `Metal`(id),
  FOREIGN KEY (styleId) REFERENCES `Styles`(id),
  FOREIGN KEY (sizeId) REFERENCES `Sizes`(id)
);